name: appperpus_app
version: 1.0.0+1
publish_to: none
description: Project UKK RPL 2024
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  art_sweetalert: ^0.0.5
  font_awesome_flutter: ^10.6.0
  flutter_onboarding_slider: ^1.0.11
  quickalert: ^1.0.2
  auto_size_text: ^3.0.0
  email_validator: ^2.1.16
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  lottie: ^2.0.0
  google_fonts: ^5.1.0
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo/icon_aplikasi.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo/
    - lib/assets/images/

