name: appperpus_app
version: 1.0.0+1
publish_to: none
description: Project UKK RPL 2024
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  email_validator: ^2.1.17
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  skeletonizer: ^1.1.1
  fluttertoast: ^8.2.4
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo/icon_aplikasi.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo/
    - lib/assets/images/

